# Copyright (c) 2014 SpinPunch. All rights reserved.
# Use of this source code is governed by an MIT-style license that can be
# found in the LICENSE file.

# note: runs in gamedata directory, NOT in gamedata/$GAME_ID
include Makefile.common
