# Copyright (c) 2015 Battlehouse Inc.All rights reserved.
# Use of this source code is governed by an MIT-style license that can be
# found in the LICENSE file.

# note: runs in gamedata directory, NOT in gamedata/$GAME_ID
include Makefile.common

${BUILT}/${GAME_ID}_buildings.json: ${GAME_ID}/${GAME_ID}_buildings.json
	@echo "    ${GAME_ID}_buildings.json..." && cp $< $@
