# Dockerfile for running Jupyter notebooks and publishing metrics dashboard
# build from game/ directory

FROM jupyter/scipy-notebook:29edefbcb06a

WORKDIR $HOME

USER root

RUN apt-get update && \
    apt-get install -y curl libmysqlclient-dev ssh git && \
    rm -rf /var/lib/apt/lists/*

# install envkey-source binary
RUN VERSION=$(curl https://envkey-releases.s3.amazonaws.com/latest/envkeysource-version.txt) && curl -s https://envkey-releases.s3.amazonaws.com/envkeysource/release_artifacts/$VERSION/install.sh | /bin/bash

RUN pip install envkey==2.0.7 mysqlclient awscli
# 'boto3>=1.7.84' 'botocore>=1.12.13'

# COPY aws aws
COPY gameserver gameserver
# COPY gamedata gamedata
# COPY gameclient gameclient
# COPY spinpunch-private spinpunch-private

COPY gameserver/config.json.example gameserver/config.json
COPY gameserver/analytics-env/Dockerfile-jupyter-entrypoint.sh /entrypoint.sh
COPY gameserver/analytics-env/Dockerfile-jupyter-entrypoint-with-aws-tunnel.sh /entrypoint-with-aws-tunnel.sh

# GitHub actions require the container itself to run as USER root
# Jupyter wants us to be running as USER 1000 (jovyan)
# Resolve this by su'ing to jovyan inside of the entrypoint
# USER 1000

ENV JUPYTER_PORT="8888"

ENTRYPOINT ["/entrypoint.sh"]
CMD /entrypoint.sh sh -c 'start-notebook.sh --NotebookApp.notebook_dir=gameserver/analytics-env/notebooks --port=${JUPYTER_PORT}'
