version: "3"
services:
  jupyter:
    build:
      context: ../..
      dockerfile: gameserver/analytics-env/Dockerfile-jupyter
    image: game-jupyter:latest
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_PORT=8888
      - ENVKEY # from .env file
    ports:
      - "8888:8888" # accessible as localhost:8888
    volumes:
      - ./notebooks:/home/jovyan/gameserver/analytics-env/notebooks
