#!/usr/bin/env python

# Copyright (c) 2015 SpinPunch Studios. All rights reserved.
# Use of this source code is governed by an MIT-style license that can be
# found in the LICENSE file.

# automatically generate loot_tables_client.json from loot_tables.json

import SpinConfig, SpinJSON
import AtomicFileWrite
import sys, os, getopt

if __name__ == '__main__':
    out_filename = None
    opts, args = getopt.gnu_getopt(sys.argv[1:], 'o:', [])
    for key, val in opts:
        if key == '-o': out_filename = val

    # command-line args: -o OUTFILE loot_tables.json spells1.json spells2.json ...
    loot_tables = SpinConfig.load(args[0])
    spells = {}
    for spell_json_filename in args[1:]:
        spells.update(SpinConfig.load(spell_json_filename, stripped = True))

    # loot tables that we need the client to know
    client_tables = set(['sexy_unlocked_unit'])
    for spellname, spell in spells.iteritems():
        if spell.get('loot_table'):
            if spell['loot_table'] not in loot_tables:
                raise Exception('loot_table "%s" referenced by spell "%s" not found' % (spell['loot_table'], spellname))
            client_tables.add(spell['loot_table'])

    with AtomicFileWrite.AtomicFileWrite(out_filename, 'w', ident=str(os.getpid())) as out_fd:
        print >> out_fd.fd, "// AUTO-GENERATED BY make_loot_tables_client.py"

        out = {}
        for table_name in client_tables:
            out[table_name] = loot_tables[table_name]

        SpinJSON.dump(out, out_fd.fd, pretty = True, newline = True)
        out_fd.complete()
