#!/usr/bin/env python

# Copyright (c) 2015 SpinPunch Studios. All rights reserved.
# Use of this source code is governed by an MIT-style license that can be
# found in the LICENSE file.

# automatically generate per-country Alloy SKU tables

import SpinJSON
import SpinConfig
import AtomicFileWrite

import sys, re, os, getopt, copy

import locale # for pretty number printing only
locale.setlocale(locale.LC_ALL, '')

# regular expression that matches C++-style comments
comment_remover = re.compile('//.*?$') # |/\*.*?/*/
verbose = True

if __name__ == '__main__':
    game_id = SpinConfig.game()

    opts, args = getopt.gnu_getopt(sys.argv[1:], 'uv', ['game-id=',])
    for key, val in opts:
        if key == '--game-id':
            game_id = val
        elif key == '-u':
            verbose = False

    out_fd = AtomicFileWrite.AtomicFileWrite(args[0], 'w', ident=str(os.getpid()))
    print >> out_fd.fd, "// AUTO-GENERATED BY", sys.argv[0]

    out = {}

    UNIT_BONUS = {"mf":
                  [{ "ui_bonus": "17x Unit Bonus", "ui_bonus_short": "17x Units",
                     "give_units": {"detonator_droid":8,
                                    "elevation_droid":3,
                                    "liberator":2,
                                    "warbird":2,
                                    "dragon":2,
                                    "level_by_cc": 1}, },
                   {  "ui_bonus": "11x Unit Bonus", "ui_bonus_short": "11x Units",
                      "give_units": {"detonator_droid":7,
                                     "elevation_droid":2,
                                     "liberator":1,
                                     "warbird":1,
                                     "level_by_cc": 1}, },
                   {  "ui_bonus": "7x Unit Bonus", "ui_bonus_short": "7x Units",
                      "give_units": {"detonator_droid":6,
                                     "elevation_droid":1,
                                     "level_by_cc": 1}, },
                   {  "ui_bonus": "5x Unit Bonus", "ui_bonus_short": "5x Units",
                      "give_units": {"detonator_droid":5,
                                     "level_by_cc": 1}, },
                   None,
                   None],
                  "tr": None}

    COMMENTS = [None, None, 'Most Popular', None, None, None]




    SLATES = {

               # the Scandinavian currencies allow good round numbers at the near-optimal prices
               "P175_NOK": {
                             "currency": "NOK",
                             "force_output": True, # necessary for legacy open graph objects
                             "skus": [{'alloy': 20000, 'NOK': 2000.00},
                                      {'alloy': 10000, 'NOK': 1000.00},
                                      {'alloy': 5000, 'NOK': 500.00},
                                      {'alloy': 1000, 'NOK': 100.00},
                                      {'alloy': 500, 'NOK': 50.00},
                                      {'alloy': 100, 'NOK': 10.00}] },
               "P175D1_NOK": { "kind": "D1",
                               "currency": "NOK",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 24000, 'NOK': 1999.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5},
                                        {'alloy': 11500, 'NOK': 999.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4},
                                        {'alloy': 5500, 'NOK': 499.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3},
                                        {'alloy': 1050, 'NOK': 99.99, 'nominal_alloy': 1000, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 500, 'NOK': 49.99, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },
               "P175D1SALE_NOK": { "kind": "D1SALE",
                               "currency": "NOK",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 26500, 'NOK': 1999.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5, 'ui_banner': 'SALE'},
                                        {'alloy': 13200, 'NOK': 999.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4, 'ui_banner': 'SALE'},
                                        {'alloy': 6575, 'NOK': 499.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3, 'ui_banner': 'SALE'},
                                        {'alloy': 1050, 'NOK': 99.99, 'nominal_alloy': 1050, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 500, 'NOK': 49.99, 'nominal_alloy': 500, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },
               "P175D2_NOK": { "kind": "D2", # Add 249.99 SKU following T238_purchase_ui_slates A/B test
                               "currency": "NOK",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 24000, 'NOK': 1999.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5},
                                        {'alloy': 11500, 'NOK': 999.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4},
                                        {'alloy': 5500, 'NOK': 499.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3},
                                        {'alloy': 2650, 'NOK': 249.99, 'nominal_alloy': 2500, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 1050, 'NOK': 99.99, 'nominal_alloy': 1000, 'ui_comment': None, 'ui_pile_size': 1},
                                        {'alloy': 500, 'NOK': 49.99, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },
               "P175D2SALE_NOK": { "kind": "D2SALE",
                               "currency": "NOK",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 26500, 'NOK': 1999.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5, 'ui_banner': 'SALE'},
                                        {'alloy': 13200, 'NOK': 999.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4, 'ui_banner': 'SALE'},
                                        {'alloy': 6575, 'NOK': 499.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3, 'ui_banner': 'SALE'},
                                        {'alloy': 2650, 'NOK': 249.99, 'nominal_alloy': 2500, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 1050, 'NOK': 99.99, 'nominal_alloy': 1000, 'ui_comment': None, 'ui_pile_size': 1},
                                        {'alloy': 500, 'NOK': 49.99, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },

               "P135_SEK": {
                             "currency": "SEK",
                             "force_output": True, # necessary for legacy open graph objects
                             "skus": [{'alloy': 20000, 'SEK': 2000.00},
                                      {'alloy': 10000, 'SEK': 1000.00},
                                      {'alloy': 5000, 'SEK': 500.00},
                                      {'alloy': 1000, 'SEK': 100.00},
                                      {'alloy': 500, 'SEK': 50.00},
                                      {'alloy': 100, 'SEK': 10.00}] },
               "P135D1_SEK": { "kind": "D1",
                               "currency": "SEK",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 24000, 'SEK': 1999.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5},
                                        {'alloy': 11500, 'SEK': 999.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4},
                                        {'alloy': 5500, 'SEK': 499.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3},
                                        {'alloy': 1050, 'SEK': 99.99, 'nominal_alloy': 1000, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 500, 'SEK': 49.99, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },
               "P135D1SALE_SEK": { "kind": "D1SALE",
                               "currency": "SEK",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 26500, 'SEK': 1999.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5, 'ui_banner': 'SALE'},
                                        {'alloy': 13200, 'SEK': 999.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4, 'ui_banner': 'SALE'},
                                        {'alloy': 6575, 'SEK': 499.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3, 'ui_banner': 'SALE'},
                                        {'alloy': 1050, 'SEK': 99.99, 'nominal_alloy': 1050, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 500, 'SEK': 49.99, 'nominal_alloy': 500, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },
               "P135D2_SEK": { "kind": "D2", # Add 249.99 SKU following T238_purchase_ui_slates A/B test
                               "currency": "SEK",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 24000, 'SEK': 1999.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5},
                                        {'alloy': 11500, 'SEK': 999.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4},
                                        {'alloy': 5500, 'SEK': 499.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3},
                                        {'alloy': 2650, 'SEK': 249.99, 'nominal_alloy': 2500, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 1050, 'SEK': 99.99, 'nominal_alloy': 1000, 'ui_comment': None, 'ui_pile_size': 1},
                                        {'alloy': 500, 'SEK': 49.99, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },
               "P135D2SALE_SEK": { "kind": "D2SALE",
                               "currency": "SEK",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 26500, 'SEK': 1999.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5, 'ui_banner': 'SALE'},
                                        {'alloy': 13200, 'SEK': 999.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4, 'ui_banner': 'SALE'},
                                        {'alloy': 6575, 'SEK': 499.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3, 'ui_banner': 'SALE'},
                                        {'alloy': 2650, 'SEK': 249.99, 'nominal_alloy': 2500, 'ui_comment': None, 'ui_pile_size': 2},

                                        {'alloy': 1050, 'SEK': 99.99, 'nominal_alloy': 1050, 'ui_comment': None, 'ui_pile_size': 1},
                                        {'alloy': 500, 'SEK': 49.99, 'nominal_alloy': 500, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },
               # same for GBP
               "P135L_GBP": {
                              "currency": "GBP",
                              "skus": [{'alloy': 20000, 'GBP': 200.00},
                                       {'alloy': 10000, 'GBP': 100.00},
                                       {'alloy': 5000, 'GBP': 50.00},
                                       {'alloy': 1000, 'GBP': 10.00},
                                       {'alloy': 500, 'GBP': 5.00},
                                       {'alloy': 100, 'GBP': 1.00}] },
               "P135M_GBP": { # 5 GBP min buy
                             "currency": "GBP",
                             "force_output": True, # necessary for legacy open graph objects
                             "skus": [{'alloy': 20000, 'GBP': 200.00},
                                      {'alloy': 10000, 'GBP': 100.00},
                                      {'alloy': 5000, 'GBP': 50.00},
                                      {'alloy': 2500, 'GBP': 25.00},
                                      {'alloy': 1000, 'GBP': 10.00},
                                      {'alloy': 500, 'GBP': 5.00}] },
               "P135D1_GBP": { "kind": "D1",
                               "currency": "GBP",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 24000, 'GBP': 199.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5},
                                        {'alloy': 11500, 'GBP': 99.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4},
                                        {'alloy': 5500, 'GBP': 49.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3},
                                        {'alloy': 1050, 'GBP': 9.99, 'nominal_alloy': 1000, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 500, 'GBP': 4.99, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },
               "P135D1SALE_GBP": { "kind": "D1SALE",
                               "currency": "GBP",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 26500, 'GBP': 199.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5, 'ui_banner': 'SALE'},
                                        {'alloy': 13200, 'GBP': 99.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4, 'ui_banner': 'SALE'},
                                        {'alloy': 6575, 'GBP': 49.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3, 'ui_banner': 'SALE'},
                                        {'alloy': 1050, 'GBP': 9.99, 'nominal_alloy': 1050, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 500, 'GBP': 4.99, 'nominal_alloy': 500, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },
               "P135D2_GBP": { "kind": "D2", # Add 24.99 SKU following T238_purchase_ui_slates A/B test
                               "currency": "GBP",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 24000, 'GBP': 199.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5},
                                        {'alloy': 11500, 'GBP': 99.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4},
                                        {'alloy': 5500, 'GBP': 49.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3},
                                        {'alloy': 2650, 'GBP': 24.99, 'nominal_alloy': 2500, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 1050, 'GBP': 9.99, 'nominal_alloy': 1000, 'ui_comment': None, 'ui_pile_size': 1},
                                        {'alloy': 500, 'GBP': 4.99, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },
               "P135D2SALE_GBP": { "kind": "D2SALE",
                               "currency": "GBP",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 26500, 'GBP': 199.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5, 'ui_banner': 'SALE'},
                                        {'alloy': 13200, 'GBP': 99.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4, 'ui_banner': 'SALE'},
                                        {'alloy': 6575, 'GBP': 49.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3, 'ui_banner': 'SALE'},
                                        {'alloy': 2650, 'GBP': 24.99, 'nominal_alloy': 2500, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 1050, 'GBP': 9.99, 'nominal_alloy': 1050, 'ui_comment': None, 'ui_pile_size': 1},
                                        {'alloy': 500, 'GBP': 4.99, 'nominal_alloy': 500, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },

               # same for EUR at the P135 level
               "P135L_EUR": {
                              "currency": "EUR",
                              "skus": [{'alloy': 20000, 'EUR': 200.00},
                                       {'alloy': 10000, 'EUR': 100.00},
                                       {'alloy': 5000, 'EUR': 50.00},
                                       {'alloy': 1000, 'EUR': 10.00},
                                       {'alloy': 500, 'EUR': 5.00},
                                       {'alloy': 100, 'EUR': 1.00}] },
               "P135M_EUR": { # 5 EUR min buy
                             "currency": "EUR",
                             "force_output": True, # necessary for legacy open graph objects
                             "skus": [{'alloy': 20000, 'EUR': 200.00},
                                      {'alloy': 10000, 'EUR': 100.00},
                                      {'alloy': 5000, 'EUR': 50.00},
                                      {'alloy': 2500, 'EUR': 25.00},
                                      {'alloy': 1000, 'EUR': 10.00},
                                      {'alloy': 500, 'EUR': 5.00}] },
              "P135D1_EUR": { "kind": "D1", # volume discount test 20140621
                              "currency": "EUR",
                              "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                              "skus": [{'alloy': 24000, 'EUR': 199.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5},
                                       {'alloy': 11500, 'EUR': 99.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4},
                                       {'alloy': 5500, 'EUR': 49.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3},
                                       {'alloy': 1050, 'EUR': 9.99, 'nominal_alloy': 1000, 'ui_comment': None, 'ui_pile_size': 2},
                                       {'alloy': 500, 'EUR': 4.99, 'ui_comment': None, 'ui_pile_size': 0},
                                       ] },
              "P135D1SALE_EUR": { "kind": "D1SALE",
                              "currency": "EUR",
                              "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                              "skus": [{'alloy': 26500, 'EUR': 199.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5, 'ui_banner': 'SALE'},
                                       {'alloy': 13200, 'EUR': 99.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4, 'ui_banner': 'SALE'},
                                       {'alloy': 6575, 'EUR': 49.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3, 'ui_banner': 'SALE'},
                                       {'alloy': 1050, 'EUR': 9.99, 'nominal_alloy': 1050, 'ui_comment': None, 'ui_pile_size': 2},
                                       {'alloy': 500, 'EUR': 4.99, 'nominal_alloy': 500, 'ui_comment': None, 'ui_pile_size': 0},
                                       ] },
              "P135D2_EUR": { "kind": "D2", # Add 24.99 SKU following T238_purchase_ui_slates A/B test
                              "currency": "EUR",
                              "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                              "skus": [{'alloy': 24000, 'EUR': 199.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5},
                                       {'alloy': 11500, 'EUR': 99.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4},
                                       {'alloy': 5500, 'EUR': 49.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3},
                                       {'alloy': 2650, 'EUR': 24.99, 'nominal_alloy': 2500, 'ui_comment': None, 'ui_pile_size': 2},
                                       {'alloy': 1050, 'EUR': 9.99, 'nominal_alloy': 1000, 'ui_comment': None, 'ui_pile_size': 1},
                                       {'alloy': 500, 'EUR': 4.99, 'ui_comment': None, 'ui_pile_size': 0},
                                       ] },
              "P135D2SALE_EUR": { "kind": "D2SALE",
                              "currency": "EUR",
                              "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                              "skus": [{'alloy': 26500, 'EUR': 199.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5, 'ui_banner': 'SALE'},
                                       {'alloy': 13200, 'EUR': 99.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4, 'ui_banner': 'SALE'},
                                       {'alloy': 6575, 'EUR': 49.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3, 'ui_banner': 'SALE'},
                                       {'alloy': 2650, 'EUR': 24.99, 'nominal_alloy': 2500, 'ui_comment': None, 'ui_pile_size': 2},
                                       {'alloy': 1050, 'EUR': 9.99, 'nominal_alloy': 1050, 'ui_comment': None, 'ui_pile_size': 1},
                                       {'alloy': 500, 'EUR': 4.99, 'nominal_alloy': 500, 'ui_comment': None, 'ui_pile_size': 0},
                                       ] },

               # XXX make even?
               "P150_EUR": {
                             "currency": "EUR",
                             "skus": [{'alloy': 22000, 'EUR': 169.43},
                                      {'alloy': 14000, 'EUR': 112.95},
                                      {'alloy': 4000, 'EUR': 37.65},
                                      {'alloy': 2200, 'EUR': 22.58},
                                      {'alloy': 1000, 'EUR': 11.29},
                                      {'alloy': 300, 'EUR': 3.76}] },

               "P150_QAR": {
                             "currency": "QAR",
                             "force_output": True, # necessary for legacy open graph objects
                             "skus": [{'alloy': 20000, 'QAR': 1000.00},
                                      {'alloy': 10000, 'QAR': 500.00},
                                      {'alloy': 5000, 'QAR': 250.00},
                                      {'alloy': 2000, 'QAR': 100.00},
                                      {'alloy': 1000, 'QAR': 50.00},
                                      {'alloy':  400, 'QAR': 20.00}] },
               "P150D1_QAR": { "kind": "D1", # volume discount test 20140621
                               "currency": "QAR",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 24000, 'QAR': 999.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5},
                                        {'alloy': 11500, 'QAR': 499.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4},
                                        {'alloy': 5500, 'QAR': 249.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3},
                                        {'alloy': 1050, 'QAR': 49.99, 'nominal_alloy': 1000, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 500, 'QAR': 24.99, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },
               "P150D1SALE_QAR": { "kind": "D1SALE",
                               "currency": "QAR",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 26500, 'QAR': 999.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5, 'ui_banner': 'SALE'},
                                        {'alloy': 13200, 'QAR': 499.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4, 'ui_banner': 'SALE'},
                                        {'alloy': 6575, 'QAR': 249.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3, 'ui_banner': 'SALE'},
                                        {'alloy': 1050, 'QAR': 49.99, 'nominal_alloy': 1050, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 500, 'QAR': 24.99, 'nominal_alloy': 500, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },
               "P150D2_QAR": { "kind": "D2", # Add 124.99 SKU following T238_purchase_ui_slates A/B test
                               "currency": "QAR",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 24000, 'QAR': 999.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5},
                                        {'alloy': 11500, 'QAR': 499.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4},
                                        {'alloy': 5500, 'QAR': 249.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3},
                                        {'alloy': 2650, 'QAR': 124.99, 'nominal_alloy': 2500, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 1050, 'QAR': 49.99, 'nominal_alloy': 1000, 'ui_comment': None, 'ui_pile_size': 1},
                                        {'alloy': 500, 'QAR': 24.99, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },
               "P150D2SALE_QAR": { "kind": "D2SALE",
                               "currency": "QAR",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 26500, 'QAR': 999.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5, 'ui_banner': 'SALE'},
                                        {'alloy': 13200, 'QAR': 499.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4, 'ui_banner': 'SALE'},
                                        {'alloy': 6575, 'QAR': 249.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3, 'ui_banner': 'SALE'},
                                        {'alloy': 2650, 'QAR': 124.99, 'nominal_alloy': 2500, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 1050, 'QAR': 49.99, 'nominal_alloy': 1050, 'ui_comment': None, 'ui_pile_size': 1},
                                        {'alloy': 500, 'QAR': 24.99, 'nominal_alloy': 500, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },

               "P100_BRL": {
                             "currency": "BRL",
                             "force_output": True, # necessary for legacy open graph objects
                             "skus": [{'alloy': 20000, 'BRL': 400.00},
                                      {'alloy': 10000, 'BRL': 200.00},
                                      {'alloy': 5000, 'BRL': 100.00},
                                      {'alloy': 2500, 'BRL': 50.00},
                                      {'alloy': 1000, 'BRL': 20.00},
                                      {'alloy':  500, 'BRL': 10.00}] },
              "P100D1_BRL": { "kind": "D1", # volume discount test 20140621
                              "currency": "BRL",
                              "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                              "skus": [{'alloy': 24000, 'BRL': 399.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5},
                                       {'alloy': 11500, 'BRL': 199.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4},
                                       {'alloy': 5500, 'BRL': 99.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3},
                                       {'alloy': 1050, 'BRL': 19.99, 'nominal_alloy': 1000, 'ui_comment': None, 'ui_pile_size': 2},
                                       {'alloy': 500, 'BRL': 9.99, 'ui_comment': None, 'ui_pile_size': 0},
                                       ] },
              "P100D1SALE_BRL": { "kind": "D1SALE",
                              "currency": "BRL",
                              "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                              "skus": [{'alloy': 26500, 'BRL': 399.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5, 'ui_banner': 'SALE'},
                                       {'alloy': 13200, 'BRL': 199.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4, 'ui_banner': 'SALE'},
                                       {'alloy': 6575, 'BRL': 99.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3, 'ui_banner': 'SALE'},
                                       {'alloy': 1050, 'BRL': 19.99, 'nominal_alloy': 1050, 'ui_comment': None, 'ui_pile_size': 2},
                                       {'alloy': 500, 'BRL': 9.99, 'nominal_alloy': 500, 'ui_comment': None, 'ui_pile_size': 0},
                                       ] },
              "P100D2_BRL": { "kind": "D2", # Add 49.99 SKU following T238_purchase_ui_slates A/B test
                              "currency": "BRL",
                              "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                              "skus": [{'alloy': 24000, 'BRL': 399.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5},
                                       {'alloy': 11500, 'BRL': 199.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4},
                                       {'alloy': 5500, 'BRL': 99.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3},
                                       {'alloy': 2650, 'BRL': 49.99, 'nominal_alloy': 2500, 'ui_comment': None, 'ui_pile_size': 2},
                                       {'alloy': 1050, 'BRL': 19.99, 'nominal_alloy': 1000, 'ui_comment': None, 'ui_pile_size': 1},
                                       {'alloy': 500, 'BRL': 9.99, 'ui_comment': None, 'ui_pile_size': 0},
                                       ] },
              "P100D2SALE_BRL": { "kind": "D2SALE",
                              "currency": "BRL",
                              "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                              "skus": [{'alloy': 26500, 'BRL': 399.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5, 'ui_banner': 'SALE'},
                                       {'alloy': 13200, 'BRL': 199.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4, 'ui_banner': 'SALE'},
                                       {'alloy': 6575, 'BRL': 99.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3, 'ui_banner': 'SALE'},
                                       {'alloy': 2650, 'BRL': 49.99, 'nominal_alloy': 2500, 'ui_comment': None, 'ui_pile_size': 2},
                                       {'alloy': 1050, 'BRL': 19.99, 'nominal_alloy': 1050, 'ui_comment': None, 'ui_pile_size': 1},
                                       {'alloy': 500, 'BRL': 9.99, 'nominal_alloy': 500, 'ui_comment': None, 'ui_pile_size': 0},
                                       ] },

               "P100_AED": {
                             "currency": "AED",
                             "force_output": True, # necessary for legacy open graph objects
                             "skus": [{'alloy': 27250, 'AED': 1000.00},
                                      {'alloy': 13600, 'AED': 500.00},
                                      {'alloy': 6800, 'AED': 250.00},
                                      {'alloy': 3400, 'AED': 125.00},
                                      {'alloy': 1350, 'AED': 50.00},
                                      {'alloy': 675, 'AED': 25.00}] },
               "P100D1_AED": { "kind": "D1", # volume discount test 20140621
                               "currency": "AED",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 24000, 'AED': 799.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5},
                                        {'alloy': 11500, 'AED': 399.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4},
                                        {'alloy': 5500, 'AED': 199.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3},
                                        {'alloy': 1050, 'AED': 39.99, 'nominal_alloy': 1000, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 500, 'AED': 19.99, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },
               "P100D1SALE_AED": { "kind": "D1SALE",
                               "currency": "AED",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 26500, 'AED': 799.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5, 'ui_banner': 'SALE'},
                                        {'alloy': 13200, 'AED': 399.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4, 'ui_banner': 'SALE'},
                                        {'alloy': 6575, 'AED': 199.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3, 'ui_banner': 'SALE'},
                                        {'alloy': 1050, 'AED': 39.99, 'nominal_alloy': 1050, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 500, 'AED': 19.99, 'nominal_alloy': 500, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },
               "P100D2_AED": { "kind": "D2", # Add 99.99 SKU following T238_purchase_ui_slates A/B test
                               "currency": "AED",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 24000, 'AED': 799.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5},
                                        {'alloy': 11500, 'AED': 399.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4},
                                        {'alloy': 5500, 'AED': 199.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3},
                                        {'alloy': 2650, 'AED': 99.99, 'nominal_alloy': 2500, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 1050, 'AED': 39.99, 'nominal_alloy': 1000, 'ui_comment': None, 'ui_pile_size': 1},
                                        {'alloy': 500, 'AED': 19.99, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },
               "P100D2SALE_AED": { "kind": "D2SALE",
                               "currency": "AED",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 26500, 'AED': 799.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5, 'ui_banner': 'SALE'},
                                        {'alloy': 13200, 'AED': 399.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4, 'ui_banner': 'SALE'},
                                        {'alloy': 6575, 'AED': 199.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3, 'ui_banner': 'SALE'},
                                        {'alloy': 2650, 'AED': 99.99, 'nominal_alloy': 2500, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 1050, 'AED': 39.99, 'nominal_alloy': 1050, 'ui_comment': None, 'ui_pile_size': 1},
                                        {'alloy': 500, 'AED': 19.99, 'nominal_alloy': 500, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },

               "P100_DKK": {
                             "currency": "DKK",
                             "force_output": True, # necessary for legacy open graph objects
                             "skus": [{'alloy': 20000, 'DKK': 1000.00},
                                      {'alloy': 10000, 'DKK': 500.00},
                                      {'alloy': 4000, 'DKK': 200.00},
                                      {'alloy': 2000, 'DKK': 100.00},
                                      {'alloy': 1000, 'DKK': 50.00},
                                      {'alloy': 500, 'DKK': 25.00}] },
               "P100D1_DKK": { "kind": "D1",
                               "currency": "DKK",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 24000, 'DKK': 999.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5},
                                        {'alloy': 11500, 'DKK': 499.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4},
                                        {'alloy': 5500, 'DKK': 249.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3},
                                        {'alloy': 1050, 'DKK': 49.99, 'nominal_alloy': 1000, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 500, 'DKK': 24.99, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },
               "P100D1SALE_DKK": { "kind": "D1SALE",
                               "currency": "DKK",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 26500, 'DKK': 999.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5, 'ui_banner': 'SALE'},
                                        {'alloy': 13200, 'DKK': 499.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4, 'ui_banner': 'SALE'},
                                        {'alloy': 6575, 'DKK': 249.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3, 'ui_banner': 'SALE'},
                                        {'alloy': 1050, 'DKK': 49.99, 'nominal_alloy': 1050, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 500, 'DKK': 24.99, 'nominal_alloy': 500, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },
               "P100D2_DKK": { "kind": "D2", # Add 124.99 SKU following T238_purchase_ui_slates A/B test
                               "currency": "DKK",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 24000, 'DKK': 999.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5},
                                        {'alloy': 11500, 'DKK': 499.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4},
                                        {'alloy': 5500, 'DKK': 249.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3},
                                        {'alloy': 2650, 'DKK': 124.99, 'nominal_alloy': 2500, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 1050, 'DKK': 49.99, 'nominal_alloy': 1000, 'ui_comment': None, 'ui_pile_size': 1},
                                        {'alloy': 500, 'DKK': 24.99, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },
               "P100D2SALE_DKK": { "kind": "D2SALE",
                               "currency": "DKK",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 26500, 'DKK': 999.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5, 'ui_banner': 'SALE'},
                                        {'alloy': 13200, 'DKK': 499.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4, 'ui_banner': 'SALE'},
                                        {'alloy': 6575, 'DKK': 249.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3, 'ui_banner': 'SALE'},
                                        {'alloy': 2650, 'DKK': 124.99, 'nominal_alloy': 2500, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 1050, 'DKK': 49.99, 'nominal_alloy': 1050, 'ui_comment': None, 'ui_pile_size': 1},
                                        {'alloy': 500, 'DKK': 24.99, 'nominal_alloy': 500, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },

               # XXX make even?
               "P150_USD": {
                             "currency": "USD",
                             "skus": [{'alloy': 22000, 'USD': 224.99},
                                      {'alloy': 14000, 'USD': 149.99},
                                      {'alloy': 4000, 'USD': 49.99},
                                      {'alloy': 2200, 'USD': 29.99},
                                      {'alloy': 1000, 'USD': 14.99},
                                      {'alloy': 300, 'USD': 4.99},
                                      ] },

               "P100L_AUD": {
                             "currency": "AUD",
                              "skus": [{'alloy': 20000, 'AUD': 200.0},
                                       {'alloy': 10000, 'AUD': 100.0},
                                       {'alloy': 5000, 'AUD': 50.0},
                                       {'alloy': 1000, 'AUD': 10.0},
                                       {'alloy': 500, 'AUD': 5.0},
                                       {'alloy': 100, 'AUD': 1.0},
                                       ] },
               "P100M_AUD": {
                             "currency": "AUD",
                             "force_output": True, # necessary for legacy open graph objects
                              "skus": [{'alloy': 20000, 'AUD': 200.0},
                                       {'alloy': 10000, 'AUD': 100.0},
                                       {'alloy': 5000, 'AUD': 50.0},
                                       {'alloy': 2500, 'AUD': 25.0},
                                       {'alloy': 1000, 'AUD': 10.0},
                                       {'alloy': 500, 'AUD': 5.0}
                                       ] },
               "P100D1_AUD": { "kind": "D1",
                               "currency": "AUD",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 24000, 'AUD': 199.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5},
                                        {'alloy': 11500, 'AUD': 99.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4},
                                        {'alloy': 5500, 'AUD': 49.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3},
                                        {'alloy': 1050, 'AUD': 9.99, 'nominal_alloy': 1000, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 500, 'AUD': 4.99, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },
               "P100D1SALE_AUD": { "kind": "D1SALE",
                               "currency": "AUD",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 26500, 'AUD': 199.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5, 'ui_banner': 'SALE'},
                                        {'alloy': 13200, 'AUD': 99.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4, 'ui_banner': 'SALE'},
                                        {'alloy': 6575, 'AUD': 49.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3, 'ui_banner': 'SALE'},
                                        {'alloy': 1050, 'AUD': 9.99, 'nominal_alloy': 1050, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 500, 'AUD': 4.99, 'nominal_alloy': 500, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },
               "P100D2_AUD": { "kind": "D2", # Add 24.99 SKU following T238_purchase_ui_slates A/B test
                               "currency": "AUD",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 24000, 'AUD': 199.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5},
                                        {'alloy': 11500, 'AUD': 99.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4},
                                        {'alloy': 5500, 'AUD': 49.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3},
                                        {'alloy': 2650, 'AUD': 24.99, 'nominal_alloy': 2500, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 1050, 'AUD': 9.99, 'nominal_alloy': 1000, 'ui_comment': None, 'ui_pile_size': 1},
                                        {'alloy': 500, 'AUD': 4.99, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },
               "P100D2SALE_AUD": { "kind": "D2SALE",
                               "currency": "AUD",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 26500, 'AUD': 199.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5, 'ui_banner': 'SALE'},
                                        {'alloy': 13200, 'AUD': 99.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4, 'ui_banner': 'SALE'},
                                        {'alloy': 6575, 'AUD': 49.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3, 'ui_banner': 'SALE'},
                                        {'alloy': 2650, 'AUD': 24.99, 'nominal_alloy': 2500, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 1050, 'AUD': 9.99, 'nominal_alloy': 1050, 'ui_comment': None, 'ui_pile_size': 1},
                                        {'alloy': 500, 'AUD': 4.99, 'nominal_alloy': 500, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },

               "P080_NZD": {
                             "currency": "NZD",
                              "skus": [{'alloy': 20000, 'NZD': 200.0},
                                       {'alloy': 10000, 'NZD': 100.0},
                                       {'alloy': 5000, 'NZD': 50.0},
                                       {'alloy': 1000, 'NZD': 10.0},
                                       {'alloy': 500, 'NZD': 5.0},
                                       {'alloy': 100, 'NZD': 1.0},
                                       ] },
               "P100M_NZD": {
                             "currency": "NZD",
                             "force_output": True, # necessary for legacy open graph objects
                              "skus": [{'alloy': 20000, 'NZD': 250.0},
                                       {'alloy': 10000, 'NZD': 125.0},
                                       {'alloy': 5000, 'NZD': 62.50},
                                       {'alloy': 2500, 'NZD': 31.25},
                                       {'alloy': 1000, 'NZD': 12.50},
                                       {'alloy': 500, 'NZD': 6.25},
                                       #{'alloy': 100, 'NZD': 1.25},
                                       ] },
               "P080D1_NZD": { "kind": "D1",
                               "currency": "NZD",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 24000, 'NZD': 199.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5},
                                        {'alloy': 11500, 'NZD': 99.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4},
                                        {'alloy': 5500, 'NZD': 49.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3},
                                        {'alloy': 1050, 'NZD': 9.99, 'nominal_alloy': 1000, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 500, 'NZD': 4.99, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },
               "P080D1SALE_NZD": { "kind": "D1SALE",
                               "currency": "NZD",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 26500, 'NZD': 199.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5, 'ui_banner': 'SALE'},
                                        {'alloy': 13200, 'NZD': 99.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4, 'ui_banner': 'SALE'},
                                        {'alloy': 6575, 'NZD': 49.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3, 'ui_banner': 'SALE'},
                                        {'alloy': 1050, 'NZD': 9.99, 'nominal_alloy': 1050, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 500, 'NZD': 4.99, 'nominal_alloy': 500, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },
               "P080D2_NZD": { "kind": "D2", # Add 24.99 SKU following T238_purchase_ui_slates A/B test
                               "currency": "NZD",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 24000, 'NZD': 199.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5},
                                        {'alloy': 11500, 'NZD': 99.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4},
                                        {'alloy': 5500, 'NZD': 49.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3},
                                        {'alloy': 2650, 'NZD': 24.99, 'nominal_alloy': 2500, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 1050, 'NZD': 9.99, 'nominal_alloy': 1000, 'ui_comment': None, 'ui_pile_size': 1},
                                        {'alloy': 500, 'NZD': 4.99, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },
               "P080D2SALE_NZD": { "kind": "D2SALE",
                               "currency": "NZD",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 26500, 'NZD': 199.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5, 'ui_banner': 'SALE'},
                                        {'alloy': 13200, 'NZD': 99.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4, 'ui_banner': 'SALE'},
                                        {'alloy': 6575, 'NZD': 49.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3, 'ui_banner': 'SALE'},
                                        {'alloy': 2650, 'NZD': 24.99, 'nominal_alloy': 2500, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 1050, 'NZD': 9.99, 'nominal_alloy': 1050, 'ui_comment': None, 'ui_pile_size': 1},
                                        {'alloy': 500, 'NZD': 4.99, 'nominal_alloy': 500, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },

               "P100L_USD": { # "straight across" - no discounts, $1 min buy, $200 max
                              "currency": "USD",
                              "skus": [{'alloy': 20000, 'USD': 200.0},
                                       {'alloy': 10000, 'USD': 100.0},
                                       {'alloy': 5000, 'USD': 50.0},
                                       {'alloy': 1000, 'USD': 10.0},
                                       {'alloy': 500, 'USD': 5.0},
                                       {'alloy': 100, 'USD': 1.0},
                                       ] },
               "P100M_USD": { # "straight across" - no discounts, $5 min buy, $200 max
                              "currency": "USD",
                              "force_output": True, # necessary for legacy open graph objects
                              "skus": [{'alloy': 20000, 'USD': 200.0},
                                       {'alloy': 10000, 'USD': 100.0},
                                       {'alloy': 5000, 'USD': 50.0},
                                       {'alloy': 2500, 'USD': 25.0},
                                       {'alloy': 1000, 'USD': 10.0},
                                       {'alloy': 500, 'USD': 5.0},
                                       ] },

               "P100D1_USD": { "kind": "D1", # volume discount test 20140621
                               "currency": "USD",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 24000, 'USD': 199.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5},
                                        {'alloy': 11500, 'USD': 99.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4},
                                        {'alloy': 5500, 'USD': 49.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3},
                                        {'alloy': 1050, 'USD': 9.99, 'nominal_alloy': 1000, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 500, 'USD': 4.99, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },
               "P100D1SALE_USD": { "kind": "D1SALE",
                               "currency": "USD",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 26500, 'USD': 199.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5, 'ui_banner': 'SALE'},
                                        {'alloy': 13200, 'USD': 99.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4, 'ui_banner': 'SALE'},
                                        {'alloy': 6575, 'USD': 49.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3, 'ui_banner': 'SALE'},
                                        {'alloy': 1050, 'USD': 9.99, 'nominal_alloy': 1050, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 500, 'USD': 4.99, 'nominal_alloy': 500, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },
               "P100D2_USD": { "kind": "D2", # Add 24.99 SKU following T238_purchase_ui_slates A/B test
                               "currency": "USD",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 24000, 'USD': 199.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5},
                                        {'alloy': 11500, 'USD': 99.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4},
                                        {'alloy': 5500, 'USD': 49.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3},
                                        {'alloy': 2650, 'USD': 24.99, 'nominal_alloy': 2500, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 1050, 'USD': 9.99, 'nominal_alloy': 1000, 'ui_comment': None, 'ui_pile_size': 1},
                                        {'alloy': 500, 'USD': 4.99, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },
               "P100D2SALE_USD": { "kind": "D2SALE",
                               "currency": "USD",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 26500, 'USD': 199.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5, 'ui_banner': 'SALE'},
                                        {'alloy': 13200, 'USD': 99.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4, 'ui_banner': 'SALE'},
                                        {'alloy': 6575, 'USD': 49.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3, 'ui_banner': 'SALE'},
                                        {'alloy': 2650, 'USD': 24.99, 'nominal_alloy': 2500, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 1050, 'USD': 9.99, 'nominal_alloy': 1050, 'ui_comment': None, 'ui_pile_size': 1},
                                        {'alloy': 500, 'USD': 4.99, 'nominal_alloy': 500, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },

               "P100L_CAD": { # "straight across" - no discounts, $1 min buy, $200 max
                              "currency": "CAD",
                              "skus": [{'alloy': 20000, 'CAD': 200.0},
                                       {'alloy': 10000, 'CAD': 100.0},
                                       {'alloy': 5000, 'CAD': 50.0},
                                       {'alloy': 1000, 'CAD': 10.0},
                                       {'alloy': 500, 'CAD': 5.0},
                                       {'alloy': 100, 'CAD': 1.0},
                                       ] },
               "P100M_CAD": { # "straight across" - no discounts, $5 min buy, $200 max
                              "currency": "CAD",
                              "force_output": True, # necessary for legacy open graph objects
                              "skus": [{'alloy': 20000, 'CAD': 200.0},
                                       {'alloy': 10000, 'CAD': 100.0},
                                       {'alloy': 5000, 'CAD': 50.0},
                                       {'alloy': 2500, 'CAD': 25.0},
                                       {'alloy': 1000, 'CAD': 10.0},
                                       {'alloy': 500, 'CAD': 5.0},
                                       ] },
               "P100D1_CAD": { "kind": "D1",
                               "currency": "CAD",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 24000, 'CAD': 199.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5},
                                        {'alloy': 11500, 'CAD': 99.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4},
                                        {'alloy': 5500, 'CAD': 49.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3},
                                        {'alloy': 1050, 'CAD': 9.99, 'nominal_alloy': 1000, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 500, 'CAD': 4.99, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },
               "P100D1SALE_CAD": { "kind": "D1SALE",
                               "currency": "CAD",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 26500, 'CAD': 199.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5, 'ui_banner': 'SALE'},
                                        {'alloy': 13200, 'CAD': 99.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4, 'ui_banner': 'SALE'},
                                        {'alloy': 6575, 'CAD': 49.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3, 'ui_banner': 'SALE'},
                                        {'alloy': 1050, 'CAD': 9.99, 'nominal_alloy': 1050, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 500, 'CAD': 4.99, 'nominal_alloy': 500, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },
               "P100D2_CAD": { "kind": "D2", # Add $24.99 SKU following T238_purchase_ui_slates A/B test
                               "currency": "CAD",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 24000, 'CAD': 199.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5},
                                        {'alloy': 11500, 'CAD': 99.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4},
                                        {'alloy': 5500, 'CAD': 49.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3},
                                        {'alloy': 2650, 'CAD': 24.99, 'nominal_alloy': 2500, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 1050, 'CAD': 9.99, 'nominal_alloy': 1000, 'ui_comment': None, 'ui_pile_size': 1},
                                        {'alloy': 500, 'CAD': 4.99, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },
               "P100D2SALE_CAD": { "kind": "D2SALE",
                               "currency": "CAD",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 26500, 'CAD': 199.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5, 'ui_banner': 'SALE'},
                                        {'alloy': 13200, 'CAD': 99.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4, 'ui_banner': 'SALE'},
                                        {'alloy': 6575, 'CAD': 49.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3, 'ui_banner': 'SALE'},
                                        {'alloy': 2650, 'CAD': 24.99, 'nominal_alloy': 2500, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 1050, 'CAD': 9.99, 'nominal_alloy': 1050, 'ui_comment': None, 'ui_pile_size': 1},
                                        {'alloy': 500, 'CAD': 4.99, 'nominal_alloy': 500, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },

               "P100L_ZAR": { # "straight across" - no discounts, $1 min buy, $200 max
                              "currency": "ZAR",
                              "force_output": True, # necessary for legacy open graph objects
                              "skus": [{'alloy': 20000, 'ZAR': 2000},
                                       {'alloy': 10000, 'ZAR': 1000},
                                       {'alloy': 5000, 'ZAR': 500},
                                       {'alloy': 1000, 'ZAR': 100},
                                       {'alloy': 500, 'ZAR': 50},
                                       {'alloy': 100, 'ZAR': 10},
                                       ] },
               "P100D1_ZAR": { "kind": "D1",
                               "currency": "ZAR",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 24000, 'ZAR': 1999.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5},
                                        {'alloy': 11500, 'ZAR': 999.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4},
                                        {'alloy': 5500, 'ZAR': 499.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3},
                                        {'alloy': 1050, 'ZAR': 99.99, 'nominal_alloy': 1000, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 500, 'ZAR': 49.99, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },
               "P100D1SALE_ZAR": { "kind": "D1SALE",
                               "currency": "ZAR",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 26500, 'ZAR': 1999.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5, 'ui_banner': 'SALE'},
                                        {'alloy': 13200, 'ZAR': 999.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4, 'ui_banner': 'SALE'},
                                        {'alloy': 6575, 'ZAR': 499.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3, 'ui_banner': 'SALE'},
                                        {'alloy': 1050, 'ZAR': 99.99, 'nominal_alloy': 1050, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 500, 'ZAR': 49.99, 'nominal_alloy': 500, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },
               "P100D2_ZAR": { "kind": "D2", # Add 249.99 SKU following T238_purchase_ui_slates A/B test
                               "currency": "ZAR",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 24000, 'ZAR': 1999.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5},
                                        {'alloy': 11500, 'ZAR': 999.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4},
                                        {'alloy': 5500, 'ZAR': 499.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3},
                                        {'alloy': 2650, 'ZAR': 249.99, 'nominal_alloy': 2500, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 1050, 'ZAR': 99.99, 'nominal_alloy': 1000, 'ui_comment': None, 'ui_pile_size': 1},
                                        {'alloy': 500, 'ZAR': 49.99, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },
               "P100D2SALE_ZAR": { "kind": "D2SALE",
                               "currency": "ZAR",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 26500, 'ZAR': 1999.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5, 'ui_banner': 'SALE'},
                                        {'alloy': 13200, 'ZAR': 999.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4, 'ui_banner': 'SALE'},
                                        {'alloy': 6575, 'ZAR': 499.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3, 'ui_banner': 'SALE'},
                                        {'alloy': 2650, 'ZAR': 249.99, 'nominal_alloy': 2500, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 1050, 'ZAR': 99.99, 'nominal_alloy': 1050, 'ui_comment': None, 'ui_pile_size': 1},
                                        {'alloy': 500, 'ZAR': 49.99, 'nominal_alloy': 500, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },

               "P100L_ISK": { # "straight across" - no discounts, $1 min buy, $200 max
                              "currency": "ISK",
                              "force_output": True, # necessary for legacy open graph objects
                              "skus": [{'alloy': 20000, 'ISK': 20000},
                                       {'alloy': 10000, 'ISK': 10000},
                                       {'alloy': 5000, 'ISK': 5000},
                                       {'alloy': 1000, 'ISK': 1000},
                                       {'alloy': 500, 'ISK': 500},
                                       {'alloy': 100, 'ISK': 100},
                                       ] },
               "P100D1_ISK": { "kind": "D1",
                               "currency": "ISK",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 24000, 'ISK': 19999, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5},
                                        {'alloy': 11500, 'ISK': 9999, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4},
                                        {'alloy': 5500, 'ISK': 4999, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3},
                                        {'alloy': 1050, 'ISK': 999, 'nominal_alloy': 1000, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 500, 'ISK': 499, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },
               "P100D1SALE_ISK": { "kind": "D1SALE",
                               "currency": "ISK",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 26500, 'ISK': 19999, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5, 'ui_banner': 'SALE'},
                                        {'alloy': 13200, 'ISK': 9999, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4, 'ui_banner': 'SALE'},
                                        {'alloy': 6575, 'ISK': 4999, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3, 'ui_banner': 'SALE'},
                                        {'alloy': 1050, 'ISK': 999, 'nominal_alloy': 1050, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 500, 'ISK': 499, 'nominal_alloy': 500, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },
               "P100D2_ISK": { "kind": "D2", # Add 2499 SKU following T238_purchase_ui_slates A/B test
                               "currency": "ISK",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 24000, 'ISK': 19999, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5},
                                        {'alloy': 11500, 'ISK': 9999, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4},
                                        {'alloy': 5500, 'ISK': 4999, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3},
                                        {'alloy': 2650, 'ISK': 2499, 'nominal_alloy': 2500, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 1050, 'ISK': 999, 'nominal_alloy': 1000, 'ui_comment': None, 'ui_pile_size': 1},
                                        {'alloy': 500, 'ISK': 499, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },
               "P100D2SALE_ISK": { "kind": "D2SALE",
                               "currency": "ISK",
                               "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                               "skus": [{'alloy': 26500, 'ISK': 19999, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5, 'ui_banner': 'SALE'},
                                        {'alloy': 13200, 'ISK': 9999, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4, 'ui_banner': 'SALE'},
                                        {'alloy': 6575, 'ISK': 4999, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3, 'ui_banner': 'SALE'},
                                        {'alloy': 2650, 'ISK': 2499, 'nominal_alloy': 2500, 'ui_comment': None, 'ui_pile_size': 2},
                                        {'alloy': 1050, 'ISK': 999, 'nominal_alloy': 1050, 'ui_comment': None, 'ui_pile_size': 1},
                                        {'alloy': 500, 'ISK': 499, 'nominal_alloy': 500, 'ui_comment': None, 'ui_pile_size': 0},
                                        ] },

               # this is maintained ONLY for special-casing a few whales who got used to deprecated low-priced SKU slates
               "P050XY_TRY": { "kind": "XY",
                              "currency": "TRY",
                              "force_output": True,
                              "skus": [{'alloy': 25000, 'TRY': 150.00},
                                       {'alloy': 7500, 'TRY': 50.00},
                                       {'alloy': 2500, 'TRY': 20.00},
                                       {'alloy': 1000, 'TRY': 10.00},
                                       {'alloy': 500, 'TRY': 5.00},
                                       {'alloy': 100, 'TRY': 1.00},
                                       ] },

               # FALLBACK OPTIONS if country is not identified
               # note: obsolete with switch to new two-level indirection
               # if we want to try using different USD price points for non-US players, we
               # can do that by creating an alternate "kind" and switching based on country in the store variables.

               "FALLBACK_P100M_USD": { # same as P100M_USD
                                       "currency": "USD",
                                       "force_output": True, # necessary for legacy open graph objects
                                       "skus": [{'alloy': 20000, 'USD': 200.0},
                                                {'alloy': 10000, 'USD': 100.0},
                                                {'alloy': 5000, 'USD': 50.0},
                                                {'alloy': 2500, 'USD': 25.0},
                                                {'alloy': 1000, 'USD': 10.0},
                                                {'alloy': 500, 'USD': 5.0},
                                                ] },
               # this is the primary fallback slate
               "FALLBACK_P100D1_USD": {"kind": "D1", # same as P100D1_USD
                                       "currency": "USD",
                                       "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                                       "skus": [{'alloy': 24000, 'USD': 199.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5},
                                                {'alloy': 11500, 'USD': 99.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4},
                                                {'alloy': 5500, 'USD': 49.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3},
                                                {'alloy': 1050, 'USD': 9.99, 'nominal_alloy': 1000, 'ui_comment': None, 'ui_pile_size': 2},
                                                {'alloy': 500, 'USD': 4.99, 'ui_comment': None, 'ui_pile_size': 0},
                                                ] },
               "FALLBACK_P100D1SALE_USD": {"kind": "D1SALE", # same as P100D1SALE_USD
                                       "currency": "USD",
                                       "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                                       "skus": [{'alloy': 26500, 'USD': 199.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5, 'ui_banner': 'SALE'},
                                                {'alloy': 13200, 'USD': 99.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4, 'ui_banner': 'SALE'},
                                                {'alloy': 6575, 'USD': 49.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3, 'ui_banner': 'SALE'},
                                                {'alloy': 1050, 'USD': 9.99, 'nominal_alloy': 1050, 'ui_comment': None, 'ui_pile_size': 2},
                                                {'alloy': 500, 'USD': 4.99, 'nominal_alloy': 500, 'ui_comment': None, 'ui_pile_size': 0},
                                                ] },

               # slates for A/B testing midrange SKUs in Tier 3/4 USD countries
               "FALLBACK_P100D2_USD": { "kind": "D2", # ADD $24.99 SKU
                                        "currency": "USD",
                                        "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                                        "skus": [{'alloy': 24000, 'USD': 199.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5},
                                                 {'alloy': 11500, 'USD': 99.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4},
                                                 {'alloy': 5500, 'USD': 49.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3},
                                                 {'alloy': 2650, 'USD': 24.99, 'nominal_alloy': 2500, 'ui_comment': None, 'ui_pile_size': 2},
                                                 {'alloy': 1050, 'USD': 9.99, 'nominal_alloy': 1000, 'ui_comment': None, 'ui_pile_size': 1},
                                                 {'alloy': 500, 'USD': 4.99, 'ui_comment': None, 'ui_pile_size': 0},
                                                 ] },
               "FALLBACK_P100D2SALE_USD": {"kind": "D2SALE", # same as P100D2SALE_USD
                                       "currency": "USD",
                                       "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                                       "skus": [{'alloy': 26500, 'USD': 199.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5, 'ui_banner': 'SALE'},
                                                {'alloy': 13200, 'USD': 99.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4, 'ui_banner': 'SALE'},
                                                {'alloy': 6575, 'USD': 49.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3, 'ui_banner': 'SALE'},
                                                {'alloy': 2650, 'USD': 24.99, 'nominal_alloy': 2500, 'ui_comment': None, 'ui_pile_size': 2},
                                                {'alloy': 1050, 'USD': 9.99, 'nominal_alloy': 1050, 'ui_comment': None, 'ui_pile_size': 1},
                                                {'alloy': 500, 'USD': 4.99, 'nominal_alloy': 500, 'ui_comment': None, 'ui_pile_size': 0},
                                                ] },

               "FALLBACK_P100D3_USD": { "kind": "D3", # REPLACE $4.99 SKU at low end with $24.99 SKU in middle
                                        "currency": "USD",
                                        "force_output": True, "unit_bonus_format": "short", "ui_warning": "Limited time special offers:", "unit_bonus": None,
                                        "skus": [{'alloy': 24000, 'USD': 199.99, 'nominal_alloy': 20000, 'ui_comment': 'Best Value', 'ui_pile_size': 5},
                                                 {'alloy': 11500, 'USD': 99.99, 'nominal_alloy': 10000, 'ui_comment': None, 'ui_pile_size': 4},
                                                 {'alloy': 5500, 'USD': 49.99, 'nominal_alloy': 5000, 'ui_comment': 'Most Popular', 'ui_pile_size': 3},
                                                 {'alloy': 2650, 'USD': 24.99, 'nominal_alloy': 2500, 'ui_comment': None, 'ui_pile_size': 2},
                                                 {'alloy': 1000, 'USD': 9.99, 'ui_comment': None, 'ui_pile_size': 0},
                                                 ] },


               # this WAS the default fallback for Price Region C/D (Tier 3/4) countries prior to 2013 August 8
               # this is maintained ONLY for special-casing a few whales who got used to deprecated low-priced SKU slates
               "P050XY_USD": { # same as P050XY
                               "currency": "USD",
                               "force_output": True,
                               "skus": [{'alloy': 25000, 'USD': 75.00},
                                        #{'alloy': 16000, 'USD': 50.00},
                                        {'alloy': 7500, 'USD': 25.00},
                                        {'alloy': 2500, 'USD': 10.00},
                                        {'alloy': 1000, 'USD': 5.00},
                                        {'alloy': 500, 'USD': 2.50},
                                        {'alloy': 100, 'USD': 0.50},
                                        ] },
              }

    for slate_name, val in sorted(SLATES.items()):
        slate_kind = val.get('kind', None)
        check_level = None
        last_level = None
        last_sku = None

        for sku_index in xrange(len(val['skus'])):
            data = val['skus'][sku_index]
            unit_bonus = UNIT_BONUS[game_id][sku_index] if (UNIT_BONUS.get(game_id,None) and val.get('unit_bonus', True)) else None
            comment = data.get('ui_comment', val.get('comments',COMMENTS)[sku_index])

            sku_name = 'BUY_GAMEBUCKS_%d' % data['alloy'] + ('_UNITS' if unit_bonus else '') + '_FBP_'+slate_name

            # perform some sanity checks on pricing
            if last_sku is not None:
                # make sure SKUs are listed in descending order
                assert data['alloy'] < last_sku['alloy']

            # check for big (>50%) deviations in alloy exchange rate across SKUs
            this_level = float(data['alloy'])/data[val['currency']]
            if check_level is not None:
                delta = abs((this_level - check_level)/check_level)
                if delta > 0.33:
                    raise Exception('big deviation on SKU %s %d vs %d: check_level %f this_level %f' % (sku_name, last_sku['alloy'], data['alloy'], check_level, this_level))
            check_level = this_level

            # make sure discount factor does not decline for larger purchases
            if last_level is not None:
                if this_level > last_level:
                    raise Exception('alloy exchange rate declines on SKU: '+sku_name)
            last_level = this_level
            last_sku = data

            assert sku_name not in out
            pretty_alloy_amount = locale.format('%d', data['alloy'], True)
            sku = {
                'quantity': data['alloy'],
                'ui_name': '%GAMEBUCKS_QUANTITY %GAME_NAME %GAMEBUCKS_NAME',
                'ui_description': "%GAMEBUCKS_QUANTITY %GAME_NAME %GAMEBUCKS_NAME, which can be spent in game on speed-ups, resources, and special items",
                'activation': 'instant', # 'icon': 'store_icon_grow_perimeter',
                'paid': 1,
                'currency': 'fbpayments:'+val['currency'],
                'price_formula': 'constant',
                'price': data[val['currency']],
                'open_graph_prices': [[val['currency'],data[val['currency']]]]
                }

            if 'ui_pile_size' in data: sku['ui_pile_size'] = data['ui_pile_size']
            if 'ui_warning' in val: sku['ui_warning'] = val['ui_warning']
            if 'nominal_alloy' in data: sku['nominal_quantity'] = data['nominal_alloy']

            if 'ui_banner' in data:
               sku['ui_banner'] = data['ui_banner'] # SKU can override slate
            elif 'ui_banner' in val:
               sku['ui_banner'] = val['ui_banner']

            if comment: sku['ui_comment'] = comment

            ui_bonus_list = []
            if 'ui_bonus' in data:
                ui_bonus_list.append(data['ui_bonus'])
            if unit_bonus:
                ui_bonus_list.append(unit_bonus['ui_bonus_short' if val.get('unit_bonus_format',None) == 'short' else 'ui_bonus'])
                sku['give_units'] = unit_bonus['give_units']

            if ui_bonus_list:
                sku['ui_bonus'] = '\n'.join(ui_bonus_list)

            if 'FALLBACK' in slate_name:
                sku['requires'] = {'predicate': 'ALWAYS_FALSE'} # not used anymore
            else:
                sku['requires'] = {'predicate': 'AND', 'subpredicates':[
                    # Facebook only
                    {'predicate': 'FRAME_PLATFORM', 'platform': 'fb'},
                    {'predicate': 'GAMEDATA_VAR', 'name': 'store.buy_gamebucks_sku_currency', 'value': val['currency']},
                    {'predicate': 'GAMEDATA_VAR', 'name': 'store.buy_gamebucks_sku_kind', 'value': val.get('kind','UNUSED')},
                    ]}

            out[sku_name] = sku

            # temporary hack - generate Xsolla SKUS as well
            if 'FALLBACK' not in slate_name:
                xsolla_sku_name = 'BUY_GAMEBUCKS_%d' % data['alloy'] + ('_UNITS' if unit_bonus else '') + '_XS_'+slate_name
                xsolla_sku = copy.deepcopy(sku)
                xsolla_sku['currency'] = 'xsolla:'+val['currency']
                del xsolla_sku['open_graph_prices']
                assert xsolla_sku['requires']['subpredicates'][0] == {'predicate':'FRAME_PLATFORM', 'platform': 'fb'}
                xsolla_sku['requires']['subpredicates'][0] = {"predicate": "GAMEDATA_VAR", "name": "store.payments_api", "value":"xsolla"}
                out[xsolla_sku_name] = xsolla_sku

    out_keys = sorted(out.keys(), key = lambda x: -int(x.split('_')[2]))
    for name in out_keys:
        data = out[name]
        print >> out_fd.fd, '"%s":' % name, SpinJSON.dumps(data, pretty = False),
        if name != out_keys[-1]:
            print >> out_fd.fd, ','
        else:
            print >> out_fd.fd

    out_fd.complete()
