#!/usr/bin/env python

# Copyright (c) 2014 SpinPunch. All rights reserved.
# Use of this source code is governed by an MIT-style license that can be
# found in the LICENSE file.

# automatically generate loot_tables_client.json from loot_tables.json

import SpinJSON
import AtomicFileWrite
import sys, os, getopt

if __name__ == '__main__':
    opts, args = getopt.gnu_getopt(sys.argv[1:], '', [])

    loot_tables = SpinJSON.load(open(args[0]), 'loot_tables.json')
    out_fd = AtomicFileWrite.AtomicFileWrite(args[1], 'w', ident=str(os.getpid()))

    print >> out_fd.fd, "// AUTO-GENERATED BY make_loot_tables_client.py"

    out = {'sexy_unlocked_unit': loot_tables['sexy_unlocked_unit']}

    SpinJSON.dump(out, out_fd.fd, pretty = True, newline = True)
    out_fd.complete()
