version: 2

jobs:
  # check that we can install requirements.txt dependencies
  test_python_libs:

    working_directory: ~/repo

    docker:
      - image: circleci/python:2.7
    steps:
      - checkout:
          path: ~/repo/game

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "game/gameserver/requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-
 
      - run:
          name: Pip install
          working_directory: ~/repo/game/gameserver
          command: |
            mkdir -p ./venv
            virtualenv ./venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - game/gameserver/venv
          key: v2-dependencies-{{ checksum "game/gameserver/requirements.txt" }}

      - run:
          name: Smoke Test
          working_directory: ~/repo/game/gameserver
          command: |
            . venv/bin/activate
            python -c 'from spinlibs import SpinHTTP'

  # test building the "eg" gamedata
  make_gamedata_eg:
    docker:
      - image: bayesimpact/circleci
    steps:
      - setup_remote_docker
      - checkout:
          path: ~/repo/game
      - run:
          name: Build make-gamedata container
          working_directory: ~/repo/game
          command: |
            docker build -t make-gamedata-eg -f Dockerfile-make-gamedata .
      - run:
          name: Run make-gamedata
          command:
            docker run --rm make-gamedata-eg:latest ./make-gamedata.sh -g eg -u

  # test building the JavaScript client
  make_gameclient:
    docker:
      - image: bayesimpact/circleci
    steps:
      - setup_remote_docker
      - checkout:
          path: ~/repo/game
      - run:
          name: Build make-gameclient container
          working_directory: ~/repo/game
          command: |
            docker build -t make-gameclient -f Dockerfile-make-gameclient .
      - run:
          name: Run make-gamedata
          command:
            docker run --rm make-gameclient:latest

workflows:
  version: 2
  all_tests:
    jobs:
      - test_python_libs
      - make_gameclient
      - make_gamedata_eg
