# Copyright (c) 2015 SpinPunch. All rights reserved.
# Use of this source code is governed by an MIT-style license that can be
# found in the LICENSE file.

# perform static analysis on our Python code

check: *.py
	pyflakes *.py
