# Copyright (c) 2015 Battlehouse Inc. All rights reserved.
# Use of this source code is governed by an MIT-style license that can be
# found in the LICENSE file.

built/linebreak: linebreak.c
	gcc -o built/linebreak linebreak.c -O2 -Wall

all: built/linebreak

clean:
	rm -f built/linebreak
