#!/bin/sh
#
# This script will be executed *after* all the other init scripts.
# You can put your own initialization stuff in here if you don't
# want to do the full Sys V style init stuff.

touch /var/lock/subsys/local

# DJM - start DropBox
# MEMORY HOG su ec2-user /home/ec2-user/.dropbox-dist/dropboxd &

# DJM - configure iptables to drop packets from known DDOS attackers

# DJM - start Ransomer Rift and Mars Frontier servers
#(cd /home/ec2-user/game/gameserver && su ec2-user ./runserver.sh)
(cd /home/ec2-user/marsfrontier/gameserver && su ec2-user ./runserver.sh)

# DJM - start game admin service
#(cd /home/ec2-user/game/gameadmin && su ec2-user ./runadmin.sh)
