name: build-batch-tasks-image

on:
  push:
    branches:
      - github-automation
  workflow_dispatch:

jobs:
  build_batch_tasks_image:
    runs-on: ubuntu-latest
    name: Build Docker image to perform SpinPunch batch tasks, and push it to GitHub CR
    env:
      ENVKEY: ${{ secrets.ENVKEY_MANAGEMENT }}
    steps:
      - name: Check out game repository
        uses: actions/checkout@v2

      - name: Check out game-spinpunch-private repository
        uses: actions/checkout@v2
        with:
          repository: spinpunch/game-spinpunch-private
          token: ${{ secrets.GHCR_PAT }}
          path: spinpunch-private

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Packages Docker image registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile-batch-tasks
          context: .
          platforms: linux/amd64
          push: true
          tags: ghcr.io/spinpunch/game-batch-tasks:latest
