on:
  push:
    branches:
      - github-automation
  workflow_dispatch:

jobs:
  build_batch_tasks_image:
    runs-on: ubuntu-latest
    name: Build Docker image to perform SpinPunch batch tasks, and push it to GitHub Packages
    env:
      ENVKEY: ${{ secrets.ENVKEY_MANAGEMENT }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Packages Docker image registry
        uses: docker/login-action@v1 
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile-batch-tasks
          platforms: linux/amd64
          push: true
          tag_with_ref: true
          tags: docker.pkg.github.com/spinpunch/game/game-batch-tasks:latest
