name: build-jupyter-image

on:
  push:
    branches:
      - github-automation
  workflow_dispatch:

jobs:
  build_jupyter_image:
    runs-on: ubuntu-latest
    name: Build Docker image for SpinPunch Jupyter notebooks, and push it to GitHub CR
    env:
      ENVKEY: ${{ secrets.ENVKEY_MANAGEMENT }}
    steps:
      - name: Check out game repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Packages Docker image registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          file: ./gameserver/analytics-env/Dockerfile-jupyter
          context: .
          platforms: linux/amd64
          push: true
          tags: ghcr.io/spinpunch/game-jupyter:latest
