on:
  schedule:
    # Sundays at 17:00 UTC
    - cron: 0 17 * * 0
  push:
    # And on push to github-automation branch
    # and master, for testing
    branches:
      - github-automation
      - master
  workflow_dispatch:

jobs:
  update_geo_ip_database:
    name: Update SpinPunch Geo IP Location Database (weekly)
    runs-on: ubuntu-latest
    container:
      image: docker://docker.pkg.github.com/spinpunch/game/game-batch-tasks:latest
      credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      env:
        ENVKEY: ${{ secrets.ENVKEY_MANAGEMENT }}
    steps:
      - name: Run Geo IP Location Update
        run: python ./SpinGeoIP.py --put
