name: update-ip-reputation

on:
  schedule:
    # Sundays at 17:00 UTC
    - cron: 0 17 * * *
  workflow_dispatch:

jobs:
  update_ip_reputation:
    name: Update SpinPunch IP Reputation Database (weekly)
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/spinpunch/game-batch-tasks:latest
      credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      env:
        ENVKEY: ${{ secrets.ENVKEY_MANAGEMENT }}
    defaults:
      run:
        working-directory: /usr/src/app/gameserver
    steps:
      - name: Run SpinPunch IP Reputation Update
        working-directory: /usr/src/app
        # install proxy-lists module manually here to avoid bloating
        # the batch-tasks Docker image. --unsafe-perm flag is required
        # to work around puppeteer issue:
        # https://github.com/puppeteer/puppeteer/issues/5656
        run: /entrypoint.sh sh -c 'npm install -g proxy-lists --unsafe-perm && python spinpunch-private/update-ip-reputation.py'
